[mgr]
prepend_keymap = [
	{ on = "<Esc>",      run = "quit --no-cwd-file", desc = "Quit" },
	{ on = "<C-q>",      run = "escape",             desc = "Exit visual mode, clear selection, or cancel search" },
	{ on = "Q",          run = "quit",               desc = "Quit the process" },
	{ on = "q",          run = "quit --no-cwd-file", desc = "Quit without outputting cwd-file" },
	{ on = "s",          run = "search --via=rg",    desc = "Search files by content via ripgrep" },
	{ on = "S",          run = "search --via=fd --args='-u -i'", desc = "Search files by name via fd" },
	{ on = [ "g", "g" ], run = "cd --interactive",   desc = "Jump interactively" },
]

[input]
prepend_keymap = [
	{ on = "<Esc>", run = "close", desc = "Cancel input" },
]
